services:
  db:
    image: postgres:17beta2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  migration:
    build:
      context: .
      target: migration
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    depends_on:
      db:
        condition: service_healthy
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      migration:
        condition: service_completed_successfully