"""Initial Migration

Revision ID: b67a3b69899a
Revises: 
Create Date: 2025-05-31 01:19:59.430167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67a3b69899a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ExpenseOrigin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('balanceDate', sa.Date(), nullable=False),
    sa.Column('expenseOriginId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expenseOriginId'], ['ExpenseOrigin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('expenseDate', sa.Date(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('expenseOriginId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['Category.id'], ),
    sa.ForeignKeyConstraint(['expenseOriginId'], ['ExpenseOrigin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Expense')
    op.drop_table('Balance')
    op.drop_table('ExpenseOrigin')
    op.drop_table('Category')
    # ### end Alembic commands ###
